### ISSUE TITLE
Convert to reusable action: join_and_round

### ISSUE THREAD

**Issue by ccunningham101** [opensafely-actions/.github#2]
I'd like to convert my study into a reusable action. My study is in this repo:
[join_and_round](https://github.com/opensafely/antidepressant-prescribing-lda/blob/reformatting/analysis/join_and_round.py)

A common initial workflow for both research studies and curation efforts is to generate a panel of plots by demographic breakdowns over time. This is part 1 of that workflow which joins a user specified list of measures files into a single file, and applies rounding.
The assumes small number suppression has been applied by the measures framework, but that could be added here as well.

**Comment by iaindillingham** [comment]
Thanks for this 🙂. I've spoken to @inglesp, and we hope to be able to set aside some time during the next deck-scrubbing week[^1] to convert this scripted action to a reusable action. It's not quite as simple as "move a repo from `opensafely` to `opensafely-actions`", because we need to discuss versioning and the associated GitHub actions workflow.

[^1]: This will take place when Data Builder phase one is complete; see the pinned links in the [#team-data](https://bennettoxford.slack.com/archives/C03FB777L1M) Slack channel.

**Comment by iaindillingham** [comment]
Do you think there's still a need for this reusable action @ccunningham101? ehrQL's measures framework produces a single measures file (the joining part) and also applies disclosure control (the rounding part). For more information, see:

* "[Using the measures framework](https://docs.opensafely.org/ehrql/explanation/measures/)"
* "[Measures](https://docs.opensafely.org/ehrql/reference/language/#measures)"
* "[How to use dummy data in an ehrQL measures definition](https://docs.opensafely.org/ehrql/how-to/dummy-measures-data/)"

As Cohort Extractor is no longer available for new studies, and as I think ehrQL's measures framework addresses the need for this reusable action, I think we can close this issue. Do you?

**Comment by ccunningham101** [comment]
I agree ehrQL covers this functionality and this issue can be closed.

**Comment by iaindillingham** [comment]
Thank you, @ccunningham101 🙂
