### ISSUE TITLE
Convert to reusable action: kaplan-meier estimates

### ISSUE THREAD

**Issue by wjchulme** [opensafely-actions/.github#5]
I'd like to convert my study into a reusable action. My study is in this repo:

https://github.com/opensafely/kaplan-meier-function

The study works locally. It already parses arguments expressed in the form `--arg value` in `project.yaml`, borrowing heavily from how this is done in the [cox-ipw](https://github.com/opensafely-actions/cox-ipw) reusable action. 

How input files, output files, variables names, etc are captured by arguments is up for discussion.

**Comment by iaindillingham** [comment]
Thanks for this 🙂. I've spoken to @inglesp, and we hope to be able to set aside some time during the next deck-scrubbing week[^1] to convert this scripted action to a reusable action. It's not quite as simple as "move a repo from `opensafely` to `opensafely-actions`", because we need to discuss versioning and the associated GitHub actions workflow.

[^1]: This will take place when Data Builder phase one is complete; see the pinned links in the [#team-data](https://bennettoxford.slack.com/archives/C03FB777L1M) Slack channel.

**Comment by iaindillingham** [comment]
The study is now a reusable action! Notice that the repo has moved from opensafely to opensafely-actions. GitHub will redirect, so you shouldn't need to change anything now (although if someone creates a new repo called opensafely/kaplan-meier-function, then you will).

Please have a look at `DEVELOPERS.md`, as this describes how new versions are tagged. Essentially, almost every merge to main will bump the patch version. We've started at v0.0.1, so the next merge to main will bump the patch version to v0.0.2. I'd strongly suggest not bumping the major or minor versions until you need to; and you many never need to. (In semver, [major version zero is for initial development](https://semver.org/spec/v2.0.0.html#spec-item-4).)

I've protected main. You should open a PR to merge to it. However, the PR need not have a reviewer. There a balance between making it clear to a user what they are getting each time a version is bumped, and making it easy for a developer to add features and fix bugs.

So, how would anyone know that this reusable action exists? Because it will soon appear on https://actions.opensafely.org/. OS Actions is updated daily, automatically. When a new version of this reusable action is bumped, then it will appear on OS Actions the next day.

And how should someone use this reusable action? Like this:

```yaml
my_kaplan_meier_function_action:
  run: kaplan-meier-function:v0.0.1
  ...
```

---

For archaeologists, here are the associated PRs:

* opensafely-actions/kaplan-meier-function#6
* opensafely-core/actions-registry#214
